-- ============================================================================
-- URL SHORTENER DATABASE SCHEMA BACKUP
-- ============================================================================
-- This script creates a complete backup of the URL Shortener Supabase database
-- and can be used to initialize a local PostgreSQL development environment.
-- 
-- Generated by MiniMax Agent on: 2025-11-06 08:14:08
-- Supabase Project: cgeyueqpzazsgtlzfvmx
-- ============================================================================

-- Set timezone for consistent behavior
SET timezone = 'UTC';

-- Enable required extensions
CREATE EXTENSION IF NOT EXISTS "pgcrypto";

-- ============================================================================
-- SEQUENCES
-- ============================================================================

-- Drop existing sequences if they exist (for clean re-creation)
DROP SEQUENCE IF EXISTS public.links_id_seq CASCADE;
DROP SEQUENCE IF EXISTS public.urls_id_seq CASCADE;
DROP SEQUENCE IF EXISTS public.url_analytics_id_seq CASCADE;

-- Create sequences
CREATE SEQUENCE public.links_id_seq
    AS bigint
    START WITH 1
    INCREMENT BY 1
    NO MINVALUE
    NO MAXVALUE
    CACHE 1;

CREATE SEQUENCE public.urls_id_seq
    AS integer
    START WITH 1
    INCREMENT BY 1
    NO MINVALUE
    MAXVALUE 2147483647
    CACHE 1;

CREATE SEQUENCE public.url_analytics_id_seq
    AS integer
    START WITH 1
    INCREMENT BY 1
    NO MINVALUE
    MAXVALUE 2147483647
    CACHE 1;

-- ============================================================================
-- TABLES
-- ============================================================================

-- Drop existing tables if they exist (for clean re-creation)
DROP TABLE IF EXISTS public.links CASCADE;
DROP TABLE IF EXISTS public.urls CASCADE;
DROP TABLE IF EXISTS public.url_analytics CASCADE;
DROP TABLE IF EXISTS public.user_profiles CASCADE;

-- ============================================================================
-- LINKS TABLE (Enhanced URL Shortening)
-- ============================================================================
CREATE TABLE public.links (
    id bigint NOT NULL DEFAULT nextval('public.links_id_seq'::regclass),
    created_at timestamp with time zone NOT NULL DEFAULT now(),
    original_url text NOT NULL,
    short_id character varying NOT NULL,
    click_count integer NOT NULL DEFAULT 0,
    custom_alias boolean NOT NULL DEFAULT false,
    last_accessed timestamp with time zone,
    metadata jsonb NOT NULL DEFAULT '{}'::jsonb,
    CONSTRAINT links_pkey PRIMARY KEY (id)
);

-- ============================================================================
-- URL_ANALYTICS TABLE (Click Tracking & Analytics)
-- ============================================================================
CREATE TABLE public.url_analytics (
    id integer NOT NULL DEFAULT nextval('public.url_analytics_id_seq'::regclass),
    url_code character varying NOT NULL,
    clicked_at timestamp without time zone DEFAULT CURRENT_TIMESTAMP,
    ip_address inet,
    user_agent text,
    referrer text,
    country character varying,
    city character varying,
    CONSTRAINT url_analytics_pkey PRIMARY KEY (id)
);

-- ============================================================================
-- URLS TABLE (Legacy URL Shortening)
-- ============================================================================
CREATE TABLE public.urls (
    id integer NOT NULL DEFAULT nextval('public.urls_id_seq'::regclass),
    url_code character varying NOT NULL,
    original_url text NOT NULL,
    created_at timestamp without time zone DEFAULT CURRENT_TIMESTAMP,
    click_count integer DEFAULT 0,
    user_id uuid,
    is_active boolean DEFAULT true,
    CONSTRAINT urls_pkey PRIMARY KEY (id),
    CONSTRAINT urls_url_code_key UNIQUE (url_code)
);

-- ============================================================================
-- USER_PROFILES TABLE (User Management)
-- ============================================================================
CREATE TABLE public.user_profiles (
    id uuid NOT NULL DEFAULT gen_random_uuid(),
    email character varying NOT NULL,
    created_at timestamp without time zone DEFAULT CURRENT_TIMESTAMP,
    updated_at timestamp without time zone DEFAULT CURRENT_TIMESTAMP,
    subscription_plan character varying DEFAULT 'free'::character varying,
    CONSTRAINT user_profiles_pkey PRIMARY KEY (id),
    CONSTRAINT user_profiles_email_key UNIQUE (email)
);

-- ============================================================================
-- INDEXES
-- ============================================================================

-- Links table indexes
CREATE UNIQUE INDEX idx_links_short_id ON public.links USING btree (short_id);
CREATE INDEX idx_links_created_at ON public.links USING btree (created_at);
CREATE INDEX idx_links_click_count ON public.links USING btree (click_count);
CREATE INDEX idx_links_last_accessed ON public.links USING btree (last_accessed);

-- Urls table indexes
CREATE UNIQUE INDEX urls_url_code_key ON public.urls USING btree (url_code);

-- User profiles indexes
CREATE UNIQUE INDEX user_profiles_email_key ON public.user_profiles USING btree (email);

-- ============================================================================
-- TRIGGERS & FUNCTIONS (Auto-updated Timestamps)
-- ============================================================================

-- Function to automatically update updated_at timestamp
CREATE OR REPLACE FUNCTION public.update_updated_at_column()
RETURNS TRIGGER AS $$
BEGIN
    NEW.updated_at = CURRENT_TIMESTAMP;
    RETURN NEW;
END;
$$ language 'plpgsql';

-- Trigger for user_profiles table
DROP TRIGGER IF EXISTS update_user_profiles_updated_at ON public.user_profiles;
CREATE TRIGGER update_user_profiles_updated_at
    BEFORE UPDATE ON public.user_profiles
    FOR EACH ROW
    EXECUTE FUNCTION public.update_updated_at_column();

-- ============================================================================
-- SAMPLE DATA (Optional - for development/testing)
-- ============================================================================

-- Insert sample links for testing (uncomment if needed)
-- INSERT INTO public.links (short_id, original_url, custom_alias, metadata) VALUES 
--     ('sample1', 'https://www.example.com/page1', false, '{"title": "Example Page 1"}'::jsonb),
--     ('sample2', 'https://www.example.com/page2', false, '{"title": "Example Page 2"}'::jsonb);

-- Insert sample analytics data (uncomment if needed)
-- INSERT INTO public.url_analytics (url_code, ip_address, user_agent, country) VALUES 
--     ('sample1', '192.168.1.1'::inet, 'Mozilla/5.0 (Windows NT 10.0; Win64; x64)', 'US'),
--     ('sample2', '192.168.1.2'::inet, 'Mozilla/5.0 (Macintosh; Intel Mac OS X 10_15_7)', 'CA');

-- Insert sample user profile (uncomment if needed)
-- INSERT INTO public.user_profiles (email, subscription_plan) VALUES 
--     ('test@example.com', 'premium');

-- ============================================================================
-- HELPFUL VIEWS (Optional - for analytics)
-- ============================================================================

-- View for link analytics summary
CREATE OR REPLACE VIEW public.link_analytics_summary AS
SELECT 
    l.short_id,
    l.original_url,
    l.click_count,
    l.created_at,
    l.last_accessed,
    l.custom_alias,
    COALESCE(analytics.click_count, 0) as total_clicks_from_analytics,
    COALESCE(analytics.unique_visitors, 0) as unique_visitors,
    COALESCE(analytics.countries, '[]'::jsonb) as countries
FROM public.links l
LEFT JOIN (
    SELECT 
        url_code,
        COUNT(*) as click_count,
        COUNT(DISTINCT ip_address) as unique_visitors,
        jsonb_agg(DISTINCT country) as countries
    FROM public.url_analytics 
    WHERE country IS NOT NULL
    GROUP BY url_code
) analytics ON l.short_id = analytics.url_code;

-- ============================================================================
-- PERMISSIONS (Basic setup for development)
-- ============================================================================

-- Grant basic permissions (adjust for your specific use case)
-- In a real application, you would set up more restrictive permissions
-- GRANT ALL PRIVILEGES ON ALL TABLES IN SCHEMA public TO postgres;
-- GRANT ALL PRIVILEGES ON ALL SEQUENCES IN SCHEMA public TO postgres;

-- ============================================================================
-- COMPLETION MESSAGE
-- ============================================================================

-- Reset sequence values to start from appropriate numbers
SELECT setval('public.links_id_seq', (SELECT MAX(id) FROM public.links));
SELECT setval('public.urls_id_seq', (SELECT MAX(id) FROM public.urls));
SELECT setval('public.url_analytics_id_seq', (SELECT MAX(id) FROM public.url_analytics));

-- Print completion message
DO $$
BEGIN
    RAISE NOTICE 'URL Shortener database schema created successfully!';
    RAISE NOTICE 'Tables created: links, urls, url_analytics, user_profiles';
    RAISE NOTICE 'Sequences created: links_id_seq, urls_id_seq, url_analytics_id_seq';
    RAISE NOTICE 'Indexes created: %', (
        SELECT COUNT(*) 
        FROM pg_indexes 
        WHERE schemaname = 'public'
    );
    RAISE NOTICE 'Views created: link_analytics_summary';
    RAISE NOTICE 'Triggers created: update_user_profiles_updated_at';
END $$;