-- URL Shortener Database Schema
-- Target: Supabase (PostgreSQL)

-- Create links table
CREATE TABLE IF NOT EXISTS links (
  id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  created_at TIMESTAMPTZ DEFAULT NOW() NOT NULL,
  original_url TEXT NOT NULL,
  short_id VARCHAR(10) NOT NULL UNIQUE,
  click_count INTEGER DEFAULT 0 NOT NULL,
  custom_alias BOOLEAN DEFAULT FALSE NOT NULL,
  last_accessed TIMESTAMPTZ,
  metadata JSONB DEFAULT '{}'::jsonb NOT NULL
);

-- Create indexes for performance
CREATE UNIQUE INDEX IF NOT EXISTS idx_links_short_id ON links(short_id);
CREATE INDEX IF NOT EXISTS idx_links_created_at ON links(created_at DESC);
CREATE INDEX IF NOT EXISTS idx_links_last_accessed ON links(last_accessed DESC);
CREATE INDEX IF NOT EXISTS idx_links_click_count ON links(click_count DESC);

-- Enable Row Level Security (RLS)
ALTER TABLE links ENABLE ROW LEVEL SECURITY;

-- Create policies for public access (no authentication required)
-- Allow anyone to select links
CREATE POLICY "Allow public read access" ON links
  FOR SELECT
  USING (true);

-- Allow anyone to insert links
CREATE POLICY "Allow public insert access" ON links
  FOR INSERT
  WITH CHECK (true);

-- Allow anyone to update links
CREATE POLICY "Allow public update access" ON links
  FOR UPDATE
  USING (true);

-- Allow anyone to delete links
CREATE POLICY "Allow public delete access" ON links
  FOR DELETE
  USING (true);

-- Create function to atomically increment click count
CREATE OR REPLACE FUNCTION increment_click_count(link_short_id VARCHAR)
RETURNS TABLE (original_url TEXT) AS $$
BEGIN
  RETURN QUERY
  UPDATE links
  SET 
    click_count = click_count + 1,
    last_accessed = NOW()
  WHERE short_id = link_short_id
  RETURNING links.original_url;
END;
$$ LANGUAGE plpgsql;

-- Create function to get analytics data
CREATE OR REPLACE FUNCTION get_analytics_summary()
RETURNS TABLE (
  total_links BIGINT,
  total_clicks BIGINT,
  avg_clicks_per_link NUMERIC
) AS $$
BEGIN
  RETURN QUERY
  SELECT 
    COUNT(*)::BIGINT as total_links,
    COALESCE(SUM(click_count), 0)::BIGINT as total_clicks,
    COALESCE(AVG(click_count), 0)::NUMERIC as avg_clicks_per_link
  FROM links;
END;
$$ LANGUAGE plpgsql;

-- Comments for documentation
COMMENT ON TABLE links IS 'Stores shortened URLs and their metadata';
COMMENT ON COLUMN links.short_id IS 'Unique identifier for the shortened URL';
COMMENT ON COLUMN links.original_url IS 'The original long URL';
COMMENT ON COLUMN links.click_count IS 'Number of times this link has been accessed';
COMMENT ON COLUMN links.custom_alias IS 'Whether the short_id was custom or auto-generated';
COMMENT ON COLUMN links.metadata IS 'Additional metadata stored as JSON';
