-- URL Shortener Database Initialization Script
-- This script creates the database schema for the URL shortener application
-- Run this in your Supabase SQL Editor or any PostgreSQL database

-- Create the links table
CREATE TABLE IF NOT EXISTS links (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    created_at TIMESTAMPTZ DEFAULT NOW() NOT NULL,
    original_url TEXT NOT NULL,
    short_id VARCHAR(10) NOT NULL,
    click_count INTEGER DEFAULT 0 NOT NULL,
    custom_alias BOOLEAN DEFAULT FALSE NOT NULL,
    last_accessed TIMESTAMPTZ,
    metadata JSONB DEFAULT '{}'::jsonb NOT NULL
);

-- Create unique index on short_id
CREATE UNIQUE INDEX IF NOT EXISTS idx_links_short_id ON links(short_id);

-- Create indexes for common queries
CREATE INDEX IF NOT EXISTS idx_links_created_at ON links(created_at);
CREATE INDEX IF NOT EXISTS idx_links_last_accessed ON links(last_accessed);

-- Create index on click_count for analytics
CREATE INDEX IF NOT EXISTS idx_links_click_count ON links(click_count);

-- Add RLS (Row Level Security) policies if needed
-- Note: Since this is a public service without authentication, RLS is disabled by default
-- You can enable RLS and create policies as needed for your use case

-- Optional: Add triggers for automatic timestamp updates
CREATE OR REPLACE FUNCTION update_updated_at_column()
RETURNS TRIGGER AS $$
BEGIN
    -- For future use if you add updated_at column
    NEW.updated_at = NOW();
    RETURN NEW;
END;
$$ language 'plpgsql';

-- Insert sample data for testing (optional)
-- Remove these lines in production
INSERT INTO links (original_url, short_id, click_count, custom_alias, metadata) VALUES
    ('https://github.com/vercel/next.js', 'nextjs', 0, true, '{"created_at": "2023-01-01T00:00:00Z"}'),
    ('https://supabase.com', 'supabase', 0, true, '{"created_at": "2023-01-02T00:00:00Z"}'),
    ('https://tailwindcss.com', 'tailwind', 0, true, '{"created_at": "2023-01-03T00:00:00Z"}')
ON CONFLICT (short_id) DO NOTHING;

-- Grant necessary permissions
-- Note: Adjust these based on your Supabase project settings
-- GRANT ALL PRIVILEGES ON TABLE links TO your_user_role;
-- GRANT USAGE, SELECT ON SEQUENCE links_id_seq TO your_user_role;

-- Comments for documentation
COMMENT ON TABLE links IS 'Stores shortened URLs and their analytics data';
COMMENT ON COLUMN links.id IS 'Primary key, auto-incrementing unique identifier';
COMMENT ON COLUMN links.created_at IS 'Timestamp when the link was created';
COMMENT ON COLUMN links.original_url IS 'The original long URL that was shortened';
COMMENT ON COLUMN links.short_id IS 'Unique short identifier for the link (4-10 characters)';
COMMENT ON COLUMN links.click_count IS 'Number of times the short link has been clicked';
COMMENT ON COLUMN links.custom_alias IS 'True if the short_id was user-provided, false if auto-generated';
COMMENT ON COLUMN links.last_accessed IS 'Timestamp when the link was last accessed';
COMMENT ON COLUMN links.metadata IS 'Additional metadata in JSON format (user agent, IP, etc.)';

-- Query to verify the schema was created correctly
SELECT 
    table_name,
    column_name,
    data_type,
    is_nullable,
    column_default
FROM information_schema.columns 
WHERE table_name = 'links'
ORDER BY ordinal_position;